CC=g++
CFLAGS=-I.

all: val_test01_solved val_test02_solved

val_test01_solved: val_test01_solved.cpp
	$(CC) -o val_test01_solved val_test01_solved.cpp

val_test02_solved: val_test02_solved.cpp
	$(CC) -o val_test02_solved val_test02_solved.cpp

clean:
	rm -f val_test01_solved val_test02_solved
